In [4]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [5]:
# Creating a Numpy Array
lst = [1, 2, 3, 4]

arr = np.array(lst)
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [15]:
# .dtype attribute

a = np.array([1, 1.4, "1.1, 1.2, 2.5"])
print(a.dtype)

<U32


In [19]:
"""
Size Comparison of ndarray and list objects
"""

from sys import getsizeof

lst = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14] # 56 -> 64
print(getsizeof(lst))

arr =np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]) # 104 -> 108, int: 4bytes
print(getsizeof(arr)) 

168
160


In [22]:
"""
Operations with NumPy Arrays
"""

prices = [30, 25, 40, 20, 20, 35, 50, 35]
price_arr = np.array(prices)
# With a list
new_prices = [price - 5 for price in prices]
print(new_prices)


# With a ndarray
price_arr -=5
print(price_arr)

# ** operation and np.sqrt



[25, 20, 35, 15, 15, 30, 45, 30]
[25 20 35 15 15 30 45 30]


In [35]:
"""
Exercise: Test Scores
"""

test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

test_3_fixed = test_3 + 2
print(test_3_fixed)

total_grade = test_1 + test_2 + test_3_fixed
print(total_grade)

final_grade = total_grade / 3
print(final_grade)

student_scores = np.array([test_1, test_2, test_3_fixed])
print(student_scores.shape)

jeremy_test_2 = student_scores[1, 3]
print(jeremy_test_2)

manual_adwoa_test_1 = np.array ([student_scores[0, 1], student_scores[0,2]])
print(manual_adwoa_test_1)

print(student_scores[:, -1])

[89 87 74 92 94]
[260 281 248 276 272]
[86.66666667 93.66666667 82.66666667 92.         90.66666667]
(3, 5)
93
[94 88]
[87 91 94]


In [39]:
"""
Logical Operations with Arrays
"""
# masking
a = np.array([10, 2, 2, 4, 5, 3, 9, 8, 9, 7])
mask = a > 5 
print(mask)
#select using logical operations '&' '|'
selected = a[a > 5]
print(selected)

# combined logical opertions

selected = a[(a > 5) | (a < 4)]
print(selected)

selected = a[(a > 4) & (a < 7)]
print(selected)

[ True False False False False False  True  True  True  True]
[10  9  8  9  7]
[10  2  2  3  9  8  9  7]
[5]
